# Download this file and open it in your text editor of choice, or copy from "-platform: generic" until the end into your text editor of choice, then find and replace:
#
# - PRINTER_NAME with the name of the printer instance used in naming the sensors and camera,
# - HOME_ASSISTANT_IP with the IP address of Home Assistant instance,
# - PREVIEW_INTERVAL with the interval in seconds to update the thumbnail image.
#
# By default, an empty thumbnail file on the Home Assistant machine will be displayed when a machine is on "standby" (powered on and connected but inactive), or (optionally, a different image) when "shutdown" (not connected to Klipper), or (optionally, a different image) when "printing", but no thumbnail path was found. A transparent 300x300 PNG file called "emptythumbnail.png" is provided in the GitHub repository.
#
# Then copy the modified text into your Home Assistant's cameras YAML file.
#
# The three URLs listed in this are, in this order:
# The image to display when printer is not connected.
# The image to display when printer is connected but not printing (no G-Code file loaded).
# The image to display when no thumbnail was found.
# Otherwise, the camera will display the thumbnail URL from the PRINTER_NAME_thumbnail sensor.

- platform: generic
  name: PRINTER_NAME_gcode_preview
  still_image_url: >
    {% if is_state('sensor.PRINTER_NAME_klippy_state','shutdown') %} http://HOME_ASSISTANT_IP:8123/local/emptythumbnail.png
    {% elif is_state('sensor.PRINTER_NAME_state','standby') %} http://HOME_ASSISTANT_IP:8123/local/emptythumbnail.png
    {% elif not states('sensor.PRINTER_NAME_thumbnail').endswith(".png") %} http://HOME_ASSISTANT_IP:8123/local/emptythumbnail.png
    {% else %} {{ states('sensor.PRINTER_NAME_thumbnail') }}
    {% endif %}
  scan_interval: PREVIEW_INTERVAL
  content_type: image/png
